### PR TITLE
♻️  Syntax updates

### PR DESCRIPTION
**Pull request by ekwoka**
- Reorganizes files to work better with NPM and cdn systems.
- Implements esbuild build system (included rewriting license comment to prevent auto-minification)
- Implements debug logging system (logging code is not built into final build)
- Rewrites all the code to have a simpler flow (could still be improved in other manners)
- Changes button identifier to `[data-scriptor-btn]` so as not to push for invalid html

Still does allow some invalid html (opens wrapping closings and such) That was a new thing and this PR is just refactoring

This PR reduces the final bundle size by 40%

### CODE REVIEW

**Comment by MarketingPip** [comment]
Woo-hoo! Now can you do this for all of @MarketingPipeline projects? :wink: 

Awesome job tho. Plus a more than a **thank you** for improving this project!

**Review by MarketingPip — APPROVED** [review]
Merging Scriptor.js Improvements :pen:

**Comment by MarketingPip** [comment]
@ekwoka - just seeing now this PR causes another issue. 

Previously when selecting elements that were wrapped, it would unwrap them when pressed again. 

Tho this error occurs when trying to do so now.

Text highlighted - 

image

becomes - 

image

on button press. 


When it should be removed. As the previous version did. 


As well when wrapping something like this. Another wrap should be added. (No wraps at the end)

image


But if there is wraps on the end - like this

image


they should be REMOVED.

I will unfortunately need to revert the old script if these are not addressed in another PR - tho the code was not better - the functionality for the previous version was better. If you are willing to take on this game of whack a mole & make another PR. Please let me know & I will avoid reverting the older version. (which I would prefer to do)

**Comment by ekwoka** [comment]
Interesting, those did work for me fine, at least after the biggest refactor.

Well, not the one that ensured that if the wrap was closed and reopened it didn't remove the tags anyway.

The code that was there before didn't seem to have that behavior either as I was going through it (I tried to simply refactor, not change functionality).

**Comment by MarketingPip** [comment]
Hmm this is just going off a hunch and not by looking at the code. Perhaps it has something to do with the values being in uppercase? 

If you can try using a <code>wrap</code> with lowercase value for block quote etc and see if the same result is produced.

**Comment by MarketingPip** [comment]
@ekwoka haha yup! That is the issue! 

AFK right now! But if you want to add a string to lowercase for the <code>wrap</code> attribute feel free! 

:+1:

**Comment by MarketingPip** [comment]
@ekwoka - fixed this! Should be working now - just waiting on CDN cache / purge. 

only problem now is I don't see your star on the repo! :wink: 

Thanks again for your contribution!

**Comment by ekwoka** [comment]
You should also take care of getting it published to NPM.

Just gotta login and do `npm publish`

Maybe set the version down lower than 1.0.0 first though, and change the name in the package if you don't like that one

**Comment by MarketingPip** [comment]
@ekwoka 
```

function remove_first_occurrence(str, searchstr)       {
	var index = str.indexOf(searchstr);
	if (index === -1) {
		return str;
	}
	return str.slice(0, index) + str.slice(index + searchstr.length);
}

console.log(remove_first_occurrence("<wrap>The quick brown fox jumps over the lazy <wrap> <wrap> o<wrap>g<wrap>", '<wrap>'));
```

don't know if you want to add this in. Plus possibly improve the small function I added in - (to call custom functions on button clicks) 

But I would assume this would be best way to get rid of matches etc.. 

There is some other small things like resetting carrots that need done too. 

Tho I know you're busy - I figured I would put this out there to see if you wanna help improve this project more than you already have! :+1: :smile:

**Comment by MarketingPip** [comment]
```js
function remove_first_occurrence(str, searchstr)       {
	var index = str.indexOf(searchstr);
	if (index === -1) {
		return str;
	}
	return str.slice(0, index) + str.slice(index + searchstr.length);
}

console.log(remove_first_occurrence("The <wrap> quick <wrap> brown fox jumps over the lazy dog", '<wrap>'));

function removeLastInstance(str, badtext) {
    var charpos = str.lastIndexOf(badtext);
    if (charpos<0) return str;
    ptone = str.substring(0,charpos);
    pttwo = str.substring(charpos+(badtext.length));
    return (ptone+pttwo);
}

console.log(removeLastInstance("The <wrap> quick brown fox jumps<wrap> over the<wrap> lazy dog<wrap>", '<wrap>'));

```

leaving this here if one of us gets to doing this!

**Pull request merged**
